version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mern_backend
    ports: "5000:5000"  
    environment: MONGO_URI=mongodb+srv://patilmanju4321:0123456789@cluster0.usmv7mb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    restart: always

  frontend:
    build: ./frontend
    container_name: mern_frontend
    ports: "5173:5173"
    depends_on: backend
    restart: always
